export class ContactsFakeDb
{
    public static contacts = [
        {
            'id'      : '5725a680b3249760ea21de52',
            'name'    : 'Data Analyst',
            'company': 'cc',
            'lastName': 'Keitch',
            'job':'Data Analyst',
            'avatar'  : 'assets/images/avatars/Abbott.jpg',
            'nickname': 'Royalguard',
            'x' : 'ATLAS',
        'mob':'7988 985699',
            'jobTitle': 'Data Analyst',
            'email'   : 'abbott@withinpixels.com',
            'vacancies':'    10',
            'post_date':'2020-01-30',
            'end_date':'2020-03-10',
            'phone'   : '+1-202-555-0175',
            'address' : '933 8th Street Stamford, CT 06902',
            'req':'UG,Exp-1 Yr,Age 23-30 ,Develop, implement, and maintain leading-edge analytic systems, taking complicated problems and building simple frameworks.',
            'sal':'498.46$',
        'desc':'Understand business processes, identify the correct data  sources and validate the quality of the data sources, Interface with business representatives to proactively identify opportunities and gather requirements, • Work with engineers to develop a high quality data product',
        
       
       
     
            'mapped':3,
            'birthday': '',
            'notes'   : '',
        'adminName':'Keitch',
        'adminEmail':'keitch@gmail.com',
        
        },
        {
            'id'      : '5725a680606588342058356d',
            'name'    : 'Web Developing',
            'lastName': 'Matlock',
            'job':'Data Analyst',
            'avatar'  : 'assets/images/avatars/Arnold.jpg',
            'nickname': 'Wanderer',
            'x' : 'ATLAS',
            'mob':'7988 985699',
            'jobTitle': 'Web Developing',
            'email'   : 'arnold@withinpixels.com',
            'vacancies':'5',
            'post_date':'2019-11-30',
            'end_date':'2020-02-10',
            'req':'UG, Exp-2Yrs,',
            'mapped':2,
            'phone'   : '+1-202-555-0141',
            'address' : '906 Valley Road Michigan City, IN 46360',
            'birthday': '',
            'notes'   : ''
           
        },
        {
            'id'      : '5725a68009e20d0a9e9acf2a',
            'name'    : 'Graphic Designer',
            'lastName': 'Bradbury',
            'job':'Data Analyst',
            'avatar'  : 'assets/images/avatars/Barrera.jpg',
            'nickname': 'Jackal',
            'company' : 'ATLAS',
            'jobTitle': 'Graphic Designer',
            'email'   : 'barrera@withinpixels.com',
            'vacancies':'4',
            'post_date':'2019-11-30',
            'end_date':'2020-02-10',
            'phone'   : '+1-202-555-0196',
            'req':'xx',
            'mapped':1,
            'address' : '183 River Street Passaic, NJ 07055',
            'birthday': '',
            'notes'   : '',
            'x':'A6 DIGITAL',
            'mob':'7990 859999',
        },
        {
            'id'      : '5725a6809fdd915739187ed5',
            'name'    : 'Visual Designer',
            'lastName': 'Strangeway',
            'job':'Data Analyst',
            'avatar'  : 'assets/images/avatars/Blair.jpg',
            'nickname': 'Knight',
            'company' : 'Conedubdax',
            'jobTitle': 'Visual Designer',
            'email'   : 'blair@withinpixels.com',
            'vacancies':'4',
            'post_date':'2019-11-30',
            'end_date':'2020-02-10',
            'phone'   : '+1-202-555-0118',
            'address' : '143 Jones Street Eau Claire, WI 54701',
            'mapped':2,
            'birthday': '',
            'notes'   : '',
            'x':'BEYOND',
            'mob':'7967 869099',
        },
        {
            'id'      : '5725a68007920cf75051da64',
            'name'    : 'Software Engineer',
            'lastName': 'Winters',
            'job':'Data Analyst',
            'avatar'  : 'assets/images/avatars/Boyle.jpg',
            'nickname': 'Jester',
            'company' : 'Newo',
            'jobTitle': 'oftware Engineer',
            'email'   : 'boyle@withinpixels.com',
            'vacancies':'3',
            'post_date':'2019-11-30',
            'mapped':4,
            'end_date':'2020-01-10',
            'phone'   : '+1-202-555-0177',
            'address' : '218 Pearl Street Brandon, FL 33510',
            'birthday': '',
            'notes'   : '',
            'x':'DCSL',
            'mob':'7987 459469',
        },
        {
            'id'      : '5725a68031fdbb1db2c1af47',
            'name'    : '3D Animator',
            'lastName': 'Camacho',
            'avatar'  : 'assets/images/avatars/Christy.jpg',
            'nickname': 'Mist',
            'company' : 'uniway',
            'jobTitle': '3D Animator',
            'email'   : 'christy@withinpixels.com',
            'vacancies':'6',
            'post_date':'2019-12-15',
            'end_date':'2020-02-16',
            'phone'   : '+1-202-555-0136',
            'mapped':3,
            'address' : '329 Bridge Street Desoto, TX 75115',
            'birthday': '',
            'notes'   : '',
            'x':'ATLAS',
            'mob':'7988 985699',
        },
        {
            'id'      : '5725a680bc670af746c435e2',
            'name'    : 'Multimedia Artist',
            'lastName': 'Redcliff',
            'avatar'  : 'assets/images/avatars/Copeland.jpg',
            'nickname': 'Cloudlaw',
            'company' : 'Tempron',
            'jobTitle': 'Multimedia Artist',
            'email'   : 'copeland@withinpixels.com',
            'vacancies':'2',
            'post_date':'2019-11-30',
            'mapped':4,
            'end_date':'2020-02-10',
            'phone'   : '+1-202-555-0107',
            'address' : '956 6th Avenue North Bergen, NJ 0704',
            'birthday': '',
            'notes'   : '',
            'x':'BEYOND',
            'mob':'7967 869099'        },
        {
            'id'      : '5725a680e7eb988a58ddf303',
            'name'    : 'Special Effects Artist',
            'lastName': 'Stevens',
            'avatar'  : 'assets/images/avatars/Estes.jpg',
            'nickname': 'Roamer',
            'company' : 'nam-dex',
            'jobTitle': 'Special Effects Artist',
            'email'   : 'estes@withinpixels.com',
            'vacancies':'1',
            'post_date':'2019-12-30',
            'end_date':'2020-02-10',
            'mapped':2
            ,
            'phone'   : '+1-202-555-0113',
            'address' : '664 York Street Cambridge, MA 02138',
            'birthday': '',
            'notes'   : '',
            'x':'DCSL',
            'mob':'7987 459469'
        },
        {
            'id'      : '5725a680dcb077889f758961',
            'name'    : 'Application Developer',
            'lastName': 'MacGuffin',
            'avatar'  : 'assets/images/avatars/Harper.jpg',
            'nickname': 'Tempest',
            'company' : 'runcane',
            'jobTitle': 'Application Developer',
            'email'   : 'harper@withinpixels.com',
            'vacancies':'6',
            'post_date':'2019-11-30',
            'end_date':'2020-03-10',
            'mapped':1,
            'phone'   : '+1-202-555-0173',
            'address' : '738 Route 11 Cornelius, NC 28031',
            'birthday': '',
            'notes'   : '',
            'x':'A6 DIGITAL',
            'mob':'7990 859999',
        },
        {
            'id'      : '5725a6806acf030f9341e925',
            'name'    : 'Content Developer',
            'lastName': 'Sheridan',
            'avatar'  : 'assets/images/avatars/Helen.jpg',
            'nickname': 'Magicbattler',
            'company' : 'Subhow',
            'jobTitle': 'Content Developer',
            'email'   : 'helen@withinpixels.com',
            'vacancies':'3',
            'post_date':'2019-10-30',
            'end_date':'2020-01-10',
            'phone'   : '+1-202-555-0163',
            'mapped':4,
            'address' : '194 Washington Avenue Saint Petersburg, FL 33702',
            'birthday': '',
            'notes'   : '',
            'x':'ATLAS',
            'mob':'7988 985699',
        },
        {
            'id'      : '5725a680ae1ae9a3c960d487',
            'name'    : 'Web Designer',
            'lastName': 'Cambias',
            'avatar'  : 'assets/images/avatars/Henderson.jpg',
            'nickname': 'Blizzard',
            'company' : 'Howcom',
            'jobTitle': 'Web Designer',
            'email'   : 'henderson@withinpixels.com',
            'vacancies':'2',
            'post_date':'2019-08-30',
            'end_date':'2019-11-10',
            'phone'   : '+1-202-555-0151',
            'mapped':2,
            'address' : '686 Roosevelt Avenue Oviedo, FL 32765',
            'birthday': '',
            'notes'   : '',
            'x':'BEYOND',
            'mob':'7967 869099',
        },
        {
            'id'      : '5725a680b8d240c011dd224b',
            'name'    : 'Web Developer',
            'lastName': 'Lakefield',
            'avatar'  : 'assets/images/avatars/Josefina.jpg',
            'nickname': 'Violet',
            'company' : 'Gecko',
            'jobTitle': 'Web Developer',
            'email'   : 'josefina@withinpixels.com',
            'vacancies':'1',
            'post_date':'2019-11-30',
            'end_date':'2020-03-10',
            'mapped':3
            ,
            'phone'   : '+1-202-555-0160',
            'address' : '202 Hartford Road Lynchburg, VA 24502',
            'birthday': '',
            'notes'   : '',
            'x':'DCSL',
            'mob':'7987 459469',
        },
        {
            'id'      : '5725a680b8d240c011dd224b',
            'name'    : 'Web Developer',
            'lastName': 'Lakefield',
            'avatar'  : 'assets/images/avatars/Josefina.jpg',
            'nickname': 'Violet',
            'company' : 'Gecko',
            'jobTitle': 'Web Developer',
            'email'   : 'josefina@withinpixels.com',
            'vacancies':'1',
            'post_date':'2019-11-30',
            'end_date':'2020-03-10',
            'mapped':3
            ,
            'phone'   : '+1-202-555-0160',
            'address' : '202 Hartford Road Lynchburg, VA 24502',
            'birthday': '',
            'notes'   : '',
            'x':'DCSL',
            'mob':'7987 459469',
        },
        // {
        //     'id'      : '5725a68034cb3968e1f79eac',
        //     'name'    : 'Software Designer',
        //     'lastName': 'Bletchley',
        //     'avatar'  : 'assets/images/avatars/Katina.jpg',
        //     'nickname': 'Rose',
        //     'company' : 'Lexicom',
        //     'jobTitle': 'Software Designer',
        //     'email'   : 'katina@withinpixels.com',
        //     'phone'   : '+1-202-555-0186',
        //     'address' : '219 Woodland Road Valrico, FL 33594',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a6801146cce777df2a08',
        //     'name'    : 'Software Specialist',
        //     'lastName': 'Peasegood',
        //     'avatar'  : 'assets/images/avatars/Lily.jpg',
        //     'nickname': 'Star',
        //     'company' : 'zooflex',
        //     'jobTitle': 'Software Specialist',
        //     'email'   : 'lily@withinpixels.com',
        //     'phone'   : '+1-202-555-0115',
        //     'address' : '305 Willow Drive Superior, WI 54880',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a6808a178bfd034d6ecf',
        //     'name'    : 'Software Engineer',
        //     'lastName': 'Nox',
        //     'avatar'  : 'assets/images/avatars/Mai.jpg',
        //     'nickname': 'Violetmage',
        //     'company' : 'quadzone',
        //     'jobTitle': 'Software Engineer',
        //     'email'   : 'mai@withinpixels.com',
        //     'phone'   : '+1-202-555-0199',
        //     'address' : '148 Heather Lane Mcminnville, TN 37110',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680653c265f5c79b5a9',
        //     'name'    : 'Software Architect',
        //     'lastName': 'Jaggers',
        //     'avatar'  : 'assets/images/avatars/Nancy.jpg',
        //     'nickname': 'Silverwarden',
        //     'company' : 'Opetamnix',
        //     'jobTitle': 'Software Architect',
        //     'email'   : 'nancy@withinpixels.com',
        //     'phone'   : '+1-202-555-0120',
        //     'address' : '345 Laurel Lane Union City, NJ 07087',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680bbcec3cc32a8488a',
        //     'name'    : 'Nora',
        //     'lastName': 'Franklin',
        //     'avatar'  : 'assets/images/avatars/Nora.jpg',
        //     'nickname': 'Katanachanter',
        //     'company' : 'Saoway',
        //     'jobTitle': 'Database Coordinator',
        //     'email'   : 'nora@withinpixels.com',
        //     'phone'   : '+1-202-555-0172',
        //     'address' : '572 Rose Street Summerfield, FL 34491',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a6803d87f1b77e17b62b',
        //     'name'    : 'Odessa',
        //     'lastName': 'Goodman',
        //     'avatar'  : 'assets/images/avatars/Odessa.jpg',
        //     'nickname': 'Rose',
        //     'company' : 'transace',
        //     'jobTitle': 'Database Administration Manager',
        //     'email'   : 'odessa@withinpixels.com',
        //     'phone'   : '+1-202-555-0190',
        //     'address' : '527 Jefferson Court Conyers, GA 30012',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680e87cb319bd9bd673',
        //     'name'    : 'Reyna',
        //     'lastName': 'Preece',
        //     'avatar'  : 'assets/images/avatars/Reyna.jpg',
        //     'nickname': 'Holydawn',
        //     'company' : 'Dingex',
        //     'jobTitle': 'Data Processing Planner',
        //     'email'   : 'reyna@withinpixels.com',
        //     'phone'   : '+1-202-555-0116',
        //     'address' : '297 Strawberry Lane Faribault, MN 55021',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a6802d10e277a0f35775',
        //     'name'    : 'Shauna',
        //     'lastName': 'Atherton',
        //     'avatar'  : 'assets/images/avatars/Shauna.jpg',
        //     'nickname': 'Faunasoul',
        //     'company' : 'Vivaflex',
        //     'jobTitle': 'Art Director',
        //     'email'   : 'shauna@withinpixels.com',
        //     'phone'   : '+1-202-555-0159',
        //     'address' : '928 Canterbury Court Pittsburgh, PA 15206',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680aef1e5cf26dd3d1f',
        //     'name'    : 'Shepard',
        //     'lastName': 'Rosco',
        //     'avatar'  : 'assets/images/avatars/Shepard.jpg',
        //     'nickname': 'Fireking',
        //     'company' : 'Goldenla',
        //     'jobTitle': 'Magazine Designer',
        //     'email'   : 'shepard@withinpixels.com',
        //     'phone'   : '+1-202-555-0173',
        //     'address' : '904 Ridge Road Pickerington, OH 43147',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680cd7efa56a45aea5d',
        //     'name'    : 'Tillman',
        //     'lastName': 'Lee',
        //     'avatar'  : 'assets/images/avatars/Tillman.jpg',
        //     'nickname': 'Gust',
        //     'company' : 'K-techno',
        //     'jobTitle': 'News Photographer',
        //     'email'   : 'tillman@withinpixels.com',
        //     'phone'   : '+1-202-555-0183',
        //     'address' : '447 Charles Street Dorchester, MA 02125',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a680fb65c91a82cb35e2',
        //     'name'    : 'Trevino',
        //     'lastName': 'Bush',
        //     'avatar'  : 'assets/images/avatars/Trevino.jpg',
        //     'nickname': 'Wolf',
        //     'company' : 'Dalthex',
        //     'jobTitle': 'Photojournalist',
        //     'email'   : 'trevino@withinpixels.com',
        //     'phone'   : '+1-202-555-0138',
        //     'address' : '84 Valley View Road Norman, OK 73072',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a68018c663044be49cbf',
        //     'name'    : 'Tyson',
        //     'lastName': 'Marshall',
        //     'avatar'  : 'assets/images/avatars/Tyson.jpg',
        //     'nickname': 'Honordread',
        //     'company' : 'Geocon',
        //     'jobTitle': 'Manuscript Editor',
        //     'email'   : 'tyson@withinpixels.com',
        //     'phone'   : '+1-202-555-0146',
        //     'address' : '204 Clark Street Monsey, NY 10952',
        //     'birthday': '',
        //     'notes'   : ''
        // },
        // {
        //     'id'      : '5725a6809413bf8a0a5272b1',
        //     'name'    : 'Velazquez',
        //     'lastName': 'Smethley',
        //     'avatar'  : 'assets/images/avatars/Velazquez.jpg',
        //     'nickname': 'Strifedream',
        //     'company' : 'ranex',
        //     'jobTitle': 'Publications Editor',
        //     'email'   : 'velezquez@withinpixels.com',
        //     'phone'   : '+1-202-555-0146',
        //     'address' : '261 Cleveland Street Riverside, NJ 08075',
        //     'birthday': '',
        //     'notes'   : ''
        // }
    ];

    public static user = [
        {
            'id'              : '5725a6802d10e277a0f35724',
            'name'            : 'John Doe',
            'avatar'          : 'assets/images/avatars/profile.jpg',
            'starred'         : [
                '5725a680ae1ae9a3c960d487',
                '5725a6801146cce777df2a08',
                '5725a680bbcec3cc32a8488a',
                '5725a680bc670af746c435e2',
                '5725a68009e20d0a9e9acf2a'
            ],
            'frequentContacts': [
                '5725a6809fdd915739187ed5',
                '5725a68031fdbb1db2c1af47',
                '5725a680606588342058356d',
                '5725a680e7eb988a58ddf303',
                '5725a6806acf030f9341e925',
                '5725a68034cb3968e1f79eac',
                '5725a6801146cce777df2a08',
                '5725a680653c265f5c79b5a9'
            ],
            'groups'          : [
                {
                    'id'        : '5725a6802d10e277a0f35739',
                    'name'      : 'Friends',
                    'contactIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680e87cb319bd9bd673',
                        '5725a6802d10e277a0f35775'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35749',
                    'name'      : 'Clients',
                    'contactIds': [
                        '5725a680cd7efa56a45aea5d',
                        '5725a68018c663044be49cbf',
                        '5725a6809413bf8a0a5272b1',
                        '5725a6803d87f1b77e17b62b'
                    ]
                },
                {
                    'id'        : '5725a6802d10e277a0f35329',
                    'name'      : 'Recent Workers',
                    'contactIds': [
                        '5725a680bbcec3cc32a8488a',
                        '5725a680653c265f5c79b5a9',
                        '5725a6808a178bfd034d6ecf',
                        '5725a6801146cce777df2a08'
                    ]
                }
            ]
        }
    ];
}
